import type {
  Application,
  KYCApplication,
  KYCApplicationDetail,
} from "./types";

export const APPLICATIONS: Application[] = [
  {
    id: "app-001",
    companyName: "NovaPay Financial",
    businessType: "Payment Processor",
    operatingStates: "CA, TX, NY, FL",
    productTags: ["Payments", "BaaS"],
    submissionDate: "2026-05-15",
    riskLevel: "HIGH",
    status: "RECEIVED",
  },
  {
    id: "app-002",
    companyName: "ClearLend Capital",
    businessType: "Digital Lender",
    operatingStates: "NY, NJ, CT",
    productTags: ["BaaS"],
    submissionDate: "2026-05-18",
    riskLevel: "LOW",
    status: "RECEIVED",
  },
  {
    id: "app-003",
    companyName: "SwiftCard Issuer",
    businessType: "Card Network",
    operatingStates: "CA, WA, OR",
    productTags: ["Card Issuing"],
    submissionDate: "2026-05-10",
    riskLevel: "MEDIUM",
    status: "DOCUMENT_REVIEW",
  },
  {
    id: "app-004",
    companyName: "Vault Savings Co.",
    businessType: "Neo-Bank",
    operatingStates: "TX, AZ, NM",
    productTags: ["Stored Value", "BaaS"],
    submissionDate: "2026-05-08",
    riskLevel: "LOW",
    status: "DOCUMENT_REVIEW",
  },
  {
    id: "app-005",
    companyName: "GlobalRemit Inc.",
    businessType: "Money Transmitter",
    operatingStates: "CA, TX, NY, FL, IL, WA",
    productTags: ["Payments"],
    submissionDate: "2026-04-28",
    riskLevel: "HIGH",
    status: "COMPLIANCE_REVIEW",
  },
  {
    id: "app-006",
    companyName: "BridgePay Solutions",
    businessType: "Payment Facilitator",
    operatingStates: "GA, SC, NC",
    productTags: ["Payments", "Card Issuing"],
    submissionDate: "2026-04-30",
    riskLevel: "MEDIUM",
    status: "COMPLIANCE_REVIEW",
  },
  {
    id: "app-007",
    companyName: "ApexTech Payments",
    businessType: "FinTech",
    operatingStates: "CA, NY",
    productTags: ["Payments"],
    submissionDate: "2026-04-20",
    riskLevel: "LOW",
    status: "TECH_SETUP",
  },
  {
    id: "app-008",
    companyName: "OnPoint Banking",
    businessType: "Digital Bank",
    operatingStates: "OH, MI, IN",
    productTags: ["BaaS", "Stored Value"],
    submissionDate: "2026-04-15",
    riskLevel: "MEDIUM",
    status: "TECH_SETUP",
  },
  {
    id: "app-009",
    companyName: "PrimeVault Corp",
    businessType: "Custodial Services",
    operatingStates: "DE, NY",
    productTags: ["Stored Value"],
    submissionDate: "2026-04-01",
    riskLevel: "LOW",
    status: "FINAL_APPROVAL",
  },
  {
    id: "app-010",
    companyName: "NextGen Issuing",
    businessType: "Card Issuer",
    operatingStates: "CA, TX",
    productTags: ["Card Issuing"],
    submissionDate: "2026-04-05",
    riskLevel: "MEDIUM",
    status: "FINAL_APPROVAL",
  },
];

export const KYC_APPLICATIONS: KYCApplication[] = [
  {
    id: "kyc-001",
    referenceId: "KYC-2026-00001",
    fullName: "James Carter",
    accountType: "Personal Checking",
    idVerificationStatus: "MATCH",
    riskLevel: "LOW",
    status: "APPROVED",
    submittedAt: "2026-06-01",
  },
  {
    id: "kyc-002",
    referenceId: "KYC-2026-00002",
    fullName: "Maria Santos",
    accountType: "Business Checking",
    idVerificationStatus: "PENDING",
    riskLevel: "MEDIUM",
    status: "PENDING",
    submittedAt: "2026-06-03",
  },
  {
    id: "kyc-003",
    referenceId: "KYC-2026-00003",
    fullName: "Robert Kim",
    accountType: "SBA Loan",
    idVerificationStatus: "MISMATCH",
    riskLevel: "HIGH",
    status: "ESCALATED",
    submittedAt: "2026-06-04",
  },
  {
    id: "kyc-004",
    referenceId: "KYC-2026-00004",
    fullName: "Aisha Patel",
    accountType: "Savings",
    idVerificationStatus: "MATCH",
    riskLevel: "LOW",
    status: "APPROVED",
    submittedAt: "2026-06-05",
  },
  {
    id: "kyc-005",
    referenceId: "KYC-2026-00005",
    fullName: "Thomas Wright",
    accountType: "Mortgage",
    idVerificationStatus: "MISMATCH",
    riskLevel: "HIGH",
    status: "REJECTED",
    submittedAt: "2026-06-05",
  },
  {
    id: "kyc-006",
    referenceId: "KYC-2026-00006",
    fullName: "Linda Zhou",
    accountType: "Personal Checking",
    idVerificationStatus: "PENDING",
    riskLevel: "MEDIUM",
    status: "PENDING",
    submittedAt: "2026-06-06",
  },
  {
    id: "kyc-007",
    referenceId: "KYC-2026-00007",
    fullName: "David Okafor",
    accountType: "Business Checking",
    idVerificationStatus: "MATCH",
    riskLevel: "LOW",
    status: "APPROVED",
    submittedAt: "2026-06-07",
  },
  {
    id: "kyc-008",
    referenceId: "KYC-2026-00008",
    fullName: "Sofia Hernandez",
    accountType: "SBA Loan",
    idVerificationStatus: "PENDING",
    riskLevel: "HIGH",
    status: "ESCALATED",
    submittedAt: "2026-06-08",
  },
];

export const KYC_DETAIL: KYCApplicationDetail = {
  id: "kyc-003",
  referenceId: "KYC-2026-00003",
  fullName: "Robert Kim",
  accountType: "SBA Loan",
  idVerificationStatus: "MISMATCH",
  riskLevel: "HIGH",
  status: "ESCALATED",
  submittedAt: "2026-06-04",
  dateOfBirth: "1981-03-22",
  ssn: "***-**-7842",
  citizenship: "United States",
  address: "1420 Harbor Blvd, Unit 5B, Los Angeles, CA 90021",
  phone: "(213) 555-0192",
  email: "robert.kim@example.com",
  occupation: "Business Owner",
  employer: "Kim Trading LLC",
  riskScore: 82,
  screeningResults: [
    { check: "OFAC Sanctions", result: "No Match", status: "pass" },
    { check: "PEP Screening", result: "No Match", status: "pass" },
    { check: "Global Sanctions", result: "No Match", status: "pass" },
    { check: "Adverse Media", result: "Match Found", status: "fail" },
    { check: "ChexSystems", result: "No Match", status: "pass" },
    { check: "USPS Address", result: "No Match", status: "pass" },
  ],
  documents: [
    {
      id: "doc-001",
      name: "Driver License (Front)",
      type: "Government ID",
      status: "Failed",
    },
    {
      id: "doc-002",
      name: "Driver License (Back)",
      type: "Government ID",
      status: "Pending",
    },
    {
      id: "doc-003",
      name: "Utility Bill",
      type: "Proof of Address",
      status: "Verified",
    },
  ],
  auditLogs: [
    {
      id: "log-001",
      timestamp: "2026-06-04T09:00:00Z",
      event: "Application created",
      actor: "System",
      type: "system",
    },
    {
      id: "log-002",
      timestamp: "2026-06-04T09:01:00Z",
      event: "Documents uploaded",
      actor: "Robert Kim",
      type: "user",
    },
    {
      id: "log-003",
      timestamp: "2026-06-04T09:02:00Z",
      event: "ID verification initiated",
      actor: "System",
      type: "system",
    },
    {
      id: "log-004",
      timestamp: "2026-06-04T09:03:00Z",
      event: "ID verification returned mismatch",
      actor: "System",
      type: "system",
    },
    {
      id: "log-005",
      timestamp: "2026-06-04T09:05:00Z",
      event: "Adverse media match detected",
      actor: "System",
      type: "system",
    },
    {
      id: "log-006",
      timestamp: "2026-06-04T10:30:00Z",
      event: "Application escalated for manual review",
      actor: "System",
      type: "system",
    },
  ],
};

export function getApplicationById(id: string): Application | undefined {
  return APPLICATIONS.find((a) => a.id === id);
}

export function getKYCById(id: string): KYCApplicationDetail {
  return { ...KYC_DETAIL, id };
}
